# NumPy e SciPy


In questo notebook parleremo due librerie fondamentali per il calcolo scientifico: NumPy e SciPy. Queste librerie sono ideali per lavorare con **dati numerici** e sono utilizzate da scienziati, ingegneri e ricercatori di tutto il mondo per analizzare e manipolare dati in modo efficiente

# NumPy

NumPy è il pacchetto fondamentale per il calcolo scientifico in Python. È una libreria Python che fornisce un oggetto array multidimensionale, vari oggetti derivati (come array mascherati e matrici) e un assortimento di routine per operazioni veloci sugli array, tra cui operazioni matematiche, logiche, manipolazione della forma, ordinamento, selezione, I/O, trasformate di Fourier discrete, algebra lineare di base, operazioni statistiche di base, simulazioni randomiche e molto altro.

Alla base del pacchetto NumPy c'è l'oggetto ndarray. Questo oggetto racchiude array n-dimensionali di tipi di dati omogenei, e molte operazioni vengono eseguite tramite codice compilato per garantire le prestazioni. A differenza delle sequenze Python standard, NumPy fornisce array di dimensione fissa e tutti gli elementi devono essere dello stesso tipo di dati. NumPy semplifica le operazioni matematiche e scientifiche su grandi quantità di dati e rende il codice più efficiente rispetto alle sequenze standard di Python. Molte librerie scientifiche e matematiche basate su Python utilizzano array NumPy, quindi imparare NumPy diventa fondamentale per utilizzare tali librerie in modo efficiente. NumPy sfrutta la vectorization e il broadcasting per eseguire operazioni element-wise in modo efficiente, mantenendo la semplicità di codice di Python.


## ndarray

L'oggetto principale in NumPy è l'ndarray (array multidimensionale), che rappresenta un array di elementi tutti dello stesso tipo, indicizzabili con un numero intero non negativo e dimensione fissa. L'ndarray è estremamente versatile e permette di effettuare operazioni aritmetiche su interi array e operazioni tra array e scalari.

### Creazione dell'ndarray
Per creare un ndarray è possibile utilizzare la funzione numpy.array(), passandogli una lista o una sequenza di elementi come argomento:


In [3]:
import numpy as np

# Creazione di un ndarray unidimensionale
a = np.array([1, 2, 3, 4, 5])

# Creazione di un ndarray bidimensionale
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [4]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

L'oggetto ndarray è simile alle liste in Python, ma tutte le operazioni su un ndarray sono effettuate in modo vettoriale, il che lo rende molto più veloce e più efficiente in termini di memoria.

Reshape dell'ndarray

Per modificare la forma dell'ndarray, è possibile utilizzare la funzione reshape():

In [3]:
c = np.array([1, 2, 3, 4, 5, 6])
c_reshaped = c.reshape(2, 3)
print(c_reshaped)


[[1 2 3]
 [4 5 6]]


### Creazione di ndarray con valori predefiniti

Per creare un ndarray con tutti i suoi valori impostati a 0 o 1, è possibile utilizzare rispettivamente le funzioni zeros() e ones():

In [5]:
# Creazione di un ndarray con tutti i valori impostati a 0
d = np.zeros((3, 4))
print(d)

# Creazione di un ndarray con tutti i valori impostati a 1
e = np.ones((2, 2))
print(e)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [8]:
# matrice di zeri, 3x3
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Creazione di ndarray con valori casuali
Per creare un ndarray con valori casuali, è possibile utilizzare la funzione random.rand(). La funzione rand() restituisce un numero casuale compreso tra 0 e 1, mentre randn() restituisce un numero casuale distribuito secondo una Gaussiana standard.

**NB**: per avere valori interi usare np.random.randint(). 



In [11]:
# Creazione di un ndarray con valori casuali
f = np.random.rand(3, 4)*10 + 10
print(f)


[[11.16660792 19.36844052 15.38318409 16.15642354]
 [10.22275954 14.2533101  17.80065381 11.27301889]
 [19.57565858 10.16815584 14.59840686 10.34452352]]


"Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today."

### Vectorization

In NumPy, la "vectorization" si riferisce alla capacità di eseguire operazioni su intere matrici o array senza dover iterare gli elementi singolarmente. Questo è possibile grazie all'implementazione efficiente di operazioni matematiche su array e alla possibilità di utilizzare funzioni universali (ufunc) come ad esempio la somma o la moltiplicazione, su matrici e array, senza dover scrivere codice iterativo. La vectorization è un concetto fondamentale in NumPy in quanto permette di scrivere codice più semplice e più veloce.

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b # somma senza ciclare
d = a * b # prodotto senza ciclare
print(c)
print(d)

[5 7 9]
[ 4 10 18]


In [13]:
a = np.array([0, np.pi/2, np.pi])
sin_a = np.sin(a) # applicazione della funzione seno a tutto l'array
print(sin_a)


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [16]:
a = 1 + np.random.rand(10) ** 2
b = np.exp(a)
b

array([4.31266782, 2.89905911, 2.95904208, 6.68077986, 2.98157679,
       3.38039949, 4.30604091, 3.01069225, 2.99254137, 5.37575088])

In [17]:
a = np.array([1, 2, 3, 4, 5])
squared_a = a**2
print(squared_a)

[ 1  4  9 16 25]


### Indexing e masking

L' "indexing" in NumPy si riferisce alla possibilità di accedere ai singoli elementi di un array attraverso l'utilizzo di indici. Questi indici possono essere interi, slice o booleani e sono molto utili quando si vuole selezionare o manipolare porzioni specifiche di un array. La sintassi dell'indexing in NumPy è molto flessibile e permette di selezionare rapidamente i dati che si desidera manipolare.


Il masking è un concetto fondamentale in NumPy e si riferisce alla tecnica di selezionare specifici elementi di un array che soddisfano determinate condizioni booleane. In pratica, si crea una maschera booleana utilizzando una condizione booleana (per esempio, array > 0 per selezionare tutti gli elementi maggiori di zero) e si applica la maschera al nostro array originale, selezionando solo gli elementi che soddisfano la condizione. In questo modo, è possibile selezionare solo le parti dell'array che ci interessano.

In [18]:
# Creare un array con valori casuali
arr = np.random.rand(5, 5)
print(arr)

# Accedere all'elemento in posizione (2, 3)
print(arr[2, 3])

# Accedere alla seconda colonna
print(arr[:, 1])

# Accedere alla terza riga
print(arr[2, :])

# Accedere alla sottomatrice in alto a sinistra 3x3
print(arr[:3, :3])

[[0.57909902 0.44876632 0.94512827 0.05978164 0.41977314]
 [0.33397321 0.42256299 0.05804245 0.719357   0.99837052]
 [0.61483385 0.78173936 0.85202844 0.40222177 0.09253714]
 [0.61825178 0.03724562 0.20400177 0.25694622 0.32817538]
 [0.57669273 0.39273552 0.04453157 0.32476219 0.46746329]]
0.4022217694504072
[0.44876632 0.42256299 0.78173936 0.03724562 0.39273552]
[0.61483385 0.78173936 0.85202844 0.40222177 0.09253714]
[[0.57909902 0.44876632 0.94512827]
 [0.33397321 0.42256299 0.05804245]
 [0.61483385 0.78173936 0.85202844]]


In [25]:
# Accedere agli elementi minori di 0.4
mask = arr < 0.4
print(arr[arr > 0])

[0.57909902 0.44876632 0.94512827 0.05978164 0.41977314 0.33397321
 0.42256299 0.05804245 0.719357   0.99837052 0.61483385 0.78173936
 0.85202844 0.40222177 0.09253714 0.61825178 0.03724562 0.20400177
 0.25694622 0.32817538 0.57669273 0.39273552 0.04453157 0.32476219
 0.46746329]


### Broadcasting

Infine, il "broadcasting" in NumPy si riferisce alla capacità di eseguire operazioni tra array di diverse forme e dimensioni senza dover esplicitamente espandere le dimensioni degli array. Questo consente di scrivere codice più compatto ed elegante, in quanto non è necessario aggiungere codice per effettuare la "ridimensione" degli array. Inoltre, il broadcasting consente di eseguire operazioni su array con diverse dimensioni, semplificando il codice e migliorando l'efficienza computazionale.

In [19]:
a = np.array([[1], 
              [2], 
              [3]])

b = np.array([4, 5, 6])

c = a * b
c

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In questo caso, NumPy effettua automaticamente l'operazione di broadcasting "trasmettendo" il primo array (a) alle dimensioni del secondo array (b) e quindi esegue il prodotto.



In sintesi, la vectorization, l'indexing e il broadcasting sono concetti fondamentali di NumPy che permettono di scrivere codice efficiente, compatto ed elegante per il calcolo scientifico.

## SciPy

SciPy è una raccolta di algoritmi matematici e di funzioni costruite sull'estensione NumPy di Python.

Statistiche: Scipy include una vasta gamma di distribuzioni di probabilità, funzioni di densità di probabilità, funzioni di distribuzione cumulativa e statistiche descrittive.

In [9]:
from scipy.stats import norm
import numpy as np

# Calcola la densità di probabilità di una normale standard in un punto specifico
x = 0.5
mu = 0
sigma = 1
pdf = norm.pdf(x, mu, sigma)
print(pdf)

# Genera 100 campioni da una distribuzione normale
samples = norm.rvs(mu, sigma, size=100)
print(samples)

# Calcola la media e la deviazione standard campionarie
mean = np.mean(samples)
std = np.std(samples)
print(mean, std)


0.3520653267642995
[-0.06926707  0.62985899  1.1235666  -0.44872382 -0.45656358  0.68385765
  0.2978262   0.74732675 -0.35312544 -1.39535896  0.75087576 -1.11367474
  0.16775437 -1.09697986 -0.87042274 -1.28775481 -0.7686418  -0.40151287
 -0.48298027  1.30347325  0.43115784 -0.07560954 -1.64509154  0.21043568
  1.20812364 -0.76776638  0.23349923  0.18195441 -0.62695129 -1.06434794
  0.07700799  0.21658369 -1.8739728  -1.08136448 -1.89419149 -1.23843175
 -1.49133739  0.1442651  -0.94997742 -1.82442986  1.00498342  0.47225176
  0.6286588  -1.3722459  -1.15211852 -1.58628469  0.62331831 -1.52700984
 -1.42245492  0.511825    0.95255737  0.97552784 -1.16621947  0.47468253
  0.2858826  -1.49158622 -0.07009239  0.07082319  0.05192197 -0.29388475
 -0.48578111 -0.5945902  -0.80759331  0.66854724 -0.10375544 -1.32936222
  0.36358171 -1.57466137  1.25214597 -1.1945802  -1.36436072 -2.27606452
  0.15518954 -0.59013055  0.93063531 -0.19659878 -0.06910346 -1.10854443
  0.01999091 -0.19371771  0.5016

Ottimizzazione: Scipy offre un'ampia gamma di algoritmi di ottimizzazione, tra cui minimizzazione di funzioni, ottimizzazione vincolata e programmazione lineare.

In [11]:
from scipy.optimize import minimize_scalar
import numpy as np

# Definisci una funzione di cui trovare il minimo
def f(x):
    return (x+1)**2 + 1 

# Trova il minimo
res = minimize_scalar(f)
print(res)


 message: 
          Optimization terminated successfully;
          The returned value satisfies the termination criteria
          (using xtol = 1.48e-08 )
 success: True
     fun: 1.0
       x: -1.0
     nit: 4
    nfev: 8


## Esercizio 1
Crea un array NumPy bidimensionale di dimensione 3x3 con valori casuali compresi tra 0 e 1. Successivamente, ridimensiona l'array in un array unidimensionale e infine calcola il coseno di ciascun valore moltiplicato per pi greco. Stampa i risultati a schermo.

**Indizio**: Utilizza la funzione np.random.rand per generare i valori casuali. Per il reshape, utilizza il metodo reshape per modificare la forma dell'array.

In [1]:
# import della libreria
import numpy as np
# Crea un array bidimensionale 3x3 con valori casuali
arr = np.random.rand(3, 3)

# Ridimensiona l'array in unidimensionale
arr_reshaped = arr.reshape(-1,1)

# Calcola il coseno del prodotto tra i valori dell'array e pi greco (usa np.pi e np.cos)
arr_cos = np.cos(arr_reshaped*np.pi)


# Stampa l'array originale, l'array ridimensionato e l'array coseno
print("Array originale:")
print(arr)
print("Array unidim:")
print(arr_reshaped)
print("Array coseno:")
print(arr_cos)


Array originale:
[[0.86234538 0.66024752 0.16121505]
 [0.02882587 0.26720156 0.20432426]
 [0.12617618 0.76940992 0.59886666]]
Array unidim:
[[0.86234538]
 [0.66024752]
 [0.16121505]
 [0.02882587]
 [0.26720156]
 [0.20432426]
 [0.12617618]
 [0.76940992]
 [0.59886666]]
Array coseno:
[[-0.90793971]
 [-0.48243496]
 [ 0.87446136]
 [ 0.99590232]
 [ 0.66788086]
 [ 0.80095749]
 [ 0.92245918]
 [-0.74888384]
 [-0.3056288 ]]


## Esercizio 2

Dato un'array NumPy unidimensionale di 20 numeri casuali compresi tra 0 e 9, filtra i valori maggiori di 5 e seleziona solo gli elementi che si trovano nelle posizioni dispari dell'array.

**Indizio**: Utilizza il concetto di masking per filtrare i dati e l'indexing/slicing per selezionare gli elementi nelle posizioni dispari.

In [2]:
np.random.randint(0,9,20)

array([3, 8, 8, 4, 1, 3, 7, 4, 0, 6, 7, 5, 5, 4, 3, 0, 5, 3, 0, 0])

In [4]:
arr = np.random.randint(0,9,20)
arr > 5

array([False, False, False,  True,  True,  True, False,  True, False,
       False, False, False, False, False, False,  True, False,  True,
        True,  True])

In [5]:
import numpy as np

# Crea un array unidimensionale di 20 numeri casuali tra 0 e 9
arr = np.random.randint(0,9,20)

# Filtra i valori maggiori di 5
mask = arr > 5
filtered_arr = arr[mask]

# Seleziona gli elementi nelle posizioni dispari
selected_arr = filtered_arr[1::2]

# Stampa il risultato
print(selected_arr)

[6 8]


In [6]:
filtered_arr

array([6, 6, 8, 8, 8])