# NumPy e SciPy


In questo notebook parleremo due librerie fondamentali per il calcolo scientifico: NumPy e SciPy. Queste librerie sono ideali per lavorare con **dati numerici** e sono utilizzate da scienziati, ingegneri e ricercatori di tutto il mondo per analizzare e manipolare dati in modo efficiente

# NumPy

NumPy è il pacchetto fondamentale per il calcolo scientifico in Python. È una libreria Python che fornisce un oggetto array multidimensionale, vari oggetti derivati (come array mascherati e matrici) e un assortimento di routine per operazioni veloci sugli array, tra cui operazioni matematiche, logiche, manipolazione della forma, ordinamento, selezione, I/O, trasformate di Fourier discrete, algebra lineare di base, operazioni statistiche di base, simulazioni randomiche e molto altro.

Alla base del pacchetto NumPy c'è l'oggetto ndarray. Questo oggetto racchiude array n-dimensionali di tipi di dati omogenei, e molte operazioni vengono eseguite tramite codice compilato per garantire le prestazioni. A differenza delle sequenze Python standard, NumPy fornisce array di dimensione fissa e tutti gli elementi devono essere dello stesso tipo di dati. NumPy semplifica le operazioni matematiche e scientifiche su grandi quantità di dati e rende il codice più efficiente rispetto alle sequenze standard di Python. Molte librerie scientifiche e matematiche basate su Python utilizzano array NumPy, quindi imparare NumPy diventa fondamentale per utilizzare tali librerie in modo efficiente. NumPy sfrutta la vectorization e il broadcasting per eseguire operazioni element-wise in modo efficiente, mantenendo la semplicità di codice di Python.


## ndarray

L'oggetto principale in NumPy è l'ndarray (array multidimensionale), che rappresenta un array di elementi tutti dello stesso tipo, indicizzabili con un numero intero non negativo e dimensione fissa. L'ndarray è estremamente versatile e permette di effettuare operazioni aritmetiche su interi array e operazioni tra array e scalari.

### Creazione dell'ndarray
Per creare un ndarray è possibile utilizzare la funzione numpy.array(), passandogli una lista o una sequenza di elementi come argomento:


In [2]:
import numpy as np

# Creazione di un ndarray unidimensionale
a = np.array([1, 2, 3, 4, 5])

# Creazione di un ndarray bidimensionale
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


L'oggetto ndarray è simile alle liste in Python, ma tutte le operazioni su un ndarray sono effettuate in modo vettoriale, il che lo rende molto più veloce e più efficiente in termini di memoria.

Reshape dell'ndarray

Per modificare la forma dell'ndarray, è possibile utilizzare la funzione reshape():

In [3]:
c = np.array([1, 2, 3, 4, 5, 6])
c_reshaped = c.reshape(2, 3)
print(c_reshaped)


[[1 2 3]
 [4 5 6]]


### Creazione di ndarray con valori predefiniti

Per creare un ndarray con tutti i suoi valori impostati a 0 o 1, è possibile utilizzare rispettivamente le funzioni zeros() e ones():

In [4]:
# Creazione di un ndarray con tutti i valori impostati a 0
d = np.zeros((3, 4))
print(d)

# Creazione di un ndarray con tutti i valori impostati a 1
e = np.ones((2, 2))
print(e)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


### Creazione di ndarray con valori casuali
Per creare un ndarray con valori casuali, è possibile utilizzare la funzione random.rand(). La funzione rand() restituisce un numero casuale compreso tra 0 e 1, mentre randn() restituisce un numero casuale distribuito secondo una Gaussiana standard.



In [5]:
# Creazione di un ndarray con valori casuali
f = np.random.rand(3, 4)
print(f)


[[0.11685497 0.56725209 0.56685268 0.2946225 ]
 [0.2512837  0.89381486 0.06758916 0.193664  ]
 [0.9586231  0.40292846 0.45509365 0.44265986]]


"Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today."

### Vectorization

In NumPy, la "vectorization" si riferisce alla capacità di eseguire operazioni su intere matrici o array senza dover iterare gli elementi singolarmente. Questo è possibile grazie all'implementazione efficiente di operazioni matematiche su array e alla possibilità di utilizzare funzioni universali (ufunc) come ad esempio la somma o la moltiplicazione, su matrici e array, senza dover scrivere codice iterativo. La vectorization è un concetto fondamentale in NumPy in quanto permette di scrivere codice più semplice e più veloce.

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b # somma senza ciclare
d = a * b # prodotto senza ciclare
print(c)
print(d)

[5 7 9]
[ 4 10 18]


In [9]:
a = np.array([0, np.pi/2, np.pi])
sin_a = np.sin(a) # applicazione della funzione seno a tutto l'array
print(sin_a)


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [17]:
a = 1 + np.random.rand(10) ** 2
b = np.exp(a)
b

array([5.60308414, 4.80688287, 5.13865082, 3.24723127, 2.78443026,
       5.10166647, 4.61998395, 7.3836382 , 3.26588216, 3.2342753 ])

In [10]:
a = np.array([1, 2, 3, 4, 5])
squared_a = a**2
print(squared_a)

[ 1  4  9 16 25]


### Indexing e masking

L' "indexing" in NumPy si riferisce alla possibilità di accedere ai singoli elementi di un array attraverso l'utilizzo di indici. Questi indici possono essere interi, slice o booleani e sono molto utili quando si vuole selezionare o manipolare porzioni specifiche di un array. La sintassi dell'indexing in NumPy è molto flessibile e permette di selezionare rapidamente i dati che si desidera manipolare.


Il masking è un concetto fondamentale in NumPy e si riferisce alla tecnica di selezionare specifici elementi di un array che soddisfano determinate condizioni booleane. In pratica, si crea una maschera booleana utilizzando una condizione booleana (per esempio, array > 0 per selezionare tutti gli elementi maggiori di zero) e si applica la maschera al nostro array originale, selezionando solo gli elementi che soddisfano la condizione. In questo modo, è possibile selezionare solo le parti dell'array che ci interessano.

In [12]:
# Creare un array con valori casuali
arr = np.random.rand(5, 5)
print(arr)

# Accedere all'elemento in posizione (2, 3)
print(arr[2, 3])

# Accedere alla seconda colonna
print(arr[:, 1])

# Accedere alla terza riga
print(arr[2, :])

# Accedere alla sottomatrice in alto a sinistra 3x3
print(arr[:3, :3])

[[0.79893516 0.78096926 0.96852214 0.93468498 0.88217486]
 [0.23444389 0.08843059 0.93338568 0.67899542 0.07433304]
 [0.07609907 0.95724025 0.74325506 0.42071534 0.6558304 ]
 [0.23244752 0.55844375 0.81655887 0.83846379 0.79413748]
 [0.07722914 0.4496457  0.19992405 0.09971775 0.20731917]]
0.4207153376109548
[0.78096926 0.08843059 0.95724025 0.55844375 0.4496457 ]
[0.07609907 0.95724025 0.74325506 0.42071534 0.6558304 ]
[[0.79893516 0.78096926 0.96852214]
 [0.23444389 0.08843059 0.93338568]
 [0.07609907 0.95724025 0.74325506]]


In [13]:
# Accedere agli elementi maggiori di 0.5
print(arr[arr > 0.5])

[0.79893516 0.78096926 0.96852214 0.93468498 0.88217486 0.93338568
 0.67899542 0.95724025 0.74325506 0.6558304  0.55844375 0.81655887
 0.83846379 0.79413748]


### Broadcasting

Infine, il "broadcasting" in NumPy si riferisce alla capacità di eseguire operazioni tra array di diverse forme e dimensioni senza dover esplicitamente espandere le dimensioni degli array. Questo consente di scrivere codice più compatto ed elegante, in quanto non è necessario aggiungere codice per effettuare la "ridimensione" degli array. Inoltre, il broadcasting consente di eseguire operazioni su array con diverse dimensioni, semplificando il codice e migliorando l'efficienza computazionale.

In [19]:
a = np.array([[1], 
              [2], 
              [3]])

b = np.array([4, 5, 6])

c = a * b
c

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In questo caso, NumPy effettua automaticamente l'operazione di broadcasting "trasmettendo" il primo array (a) alle dimensioni del secondo array (b) e quindi esegue il prodotto.



In sintesi, la vectorization, l'indexing e il broadcasting sono concetti fondamentali di NumPy che permettono di scrivere codice efficiente, compatto ed elegante per il calcolo scientifico.

## SciPy

SciPy è una raccolta di algoritmi matematici e di funzioni costruite sull'estensione NumPy di Python.

Statistiche: Scipy include una vasta gamma di distribuzioni di probabilità, funzioni di densità di probabilità, funzioni di distribuzione cumulativa e statistiche descrittive.

In [20]:
from scipy.stats import norm
import numpy as np

# Calcola la densità di probabilità di una normale standard in un punto specifico
x = 0.5
mu = 0
sigma = 1
pdf = norm.pdf(x, mu, sigma)
print(pdf)

# Genera 100 campioni da una distribuzione normale
samples = norm.rvs(mu, sigma, size=100)
print(samples)

# Calcola la media e la deviazione standard campionarie
mean = np.mean(samples)
std = np.std(samples)
print(mean, std)


0.3520653267642995
[-7.43426712e-01  1.08013069e+00 -3.50961908e+00 -5.18118215e-01
  2.01568813e-01  8.48412626e-02 -1.46043465e-01 -1.65214560e+00
 -1.49260373e+00  1.30925210e-04 -8.69271035e-01 -1.36743080e+00
 -1.03624648e+00 -3.30248301e-01 -1.74669634e+00 -7.04236690e-01
 -7.53071740e-01  1.60408886e-01 -1.15860688e-02 -1.17925750e+00
  1.00298266e+00 -3.65802309e-01  1.55747228e+00 -7.58725559e-02
  2.35761481e+00 -8.93799384e-01 -1.16299039e+00  1.85538056e+00
  3.57524347e-04  8.01170688e-01  1.73807062e+00  7.15659544e-01
 -8.36860613e-01  5.20085833e-02  1.76697802e+00  1.20643846e+00
  2.14864601e+00 -1.96305183e+00  1.21577720e+00  4.71219393e-01
  1.01760890e+00  2.19162006e+00  8.74432484e-01  1.53326199e+00
  5.31219182e-01  8.00419147e-01  1.48056422e-01  3.68255028e-01
 -1.73696061e-01 -7.74956562e-01  9.60347346e-01 -5.47533887e-01
 -8.86504804e-01 -8.44985710e-01 -4.84858385e-01 -7.35158683e-01
  1.02515061e+00  1.09445672e+00 -1.96152244e-01 -1.11679097e+00
 -1.52

Ottimizzazione: Scipy offre un'ampia gamma di algoritmi di ottimizzazione, tra cui minimizzazione di funzioni, ottimizzazione vincolata e programmazione lineare.

In [31]:
from scipy.optimize import minimize_scalar
import numpy as np

# Definisci una funzione di cui trovare il minimo
def f(x):
    return (x+1)**2 + 1 

# Trova il minimo
res = minimize_scalar(f)
print(res)


 message: 
          Optimization terminated successfully;
          The returned value satisfies the termination criteria
          (using xtol = 1.48e-08 )
 success: True
     fun: 1.0
       x: -1.0
     nit: 4
    nfev: 8
