## Esercizio 1

Crea un array NumPy bidimensionale di dimensione 3x3 con valori casuali compresi tra 0 e 1. Successivamente, ridimensiona l'array in un array unidimensionale e infine calcola il coseno di ciascun valore moltiplicato per pi greco. Stampa i risultati a schermo.

In [14]:
import numpy as np

# Crea un array bidimensionale 3x3 con valori casuali
arr = np.random.rand(3, 3) 

# Ridimensiona l'array in unidimensionale
arr_reshaped = arr.reshape(9)

# Calcola il coseno del prodotto tra i valori dell'array e pi greco (usa np.pi e np.cos)
arr_cos = np.cos(arr_reshaped*np.pi)

# Stampa l'array originale e l'array ridimensionato
print("Array originale:")
print(arr)
print("\nArray ridimensionato:")
print(arr_reshaped)
print("\nArray coseno:")
print(arr_cos)

Array originale:
[[0.512521   0.78362221 0.02167894]
 [0.41429376 0.10157596 0.41407508]
 [0.77673098 0.06329905 0.18487647]]

Array ridimensionato:
[0.512521   0.78362221 0.02167894 0.41429376 0.10157596 0.41407508
 0.77673098 0.06329905 0.18487647]

Array coseno:
[-0.03932574 -0.77771678  0.99768165  0.26601248  0.94951491  0.26667466
 -0.76392643  0.98029246  0.83602037]


## Esercizio 2

Dato un'array NumPy unidimensionale di numeri casuali compresi tra 0 e 9, filtra i valori maggiori di 5 e seleziona solo gli elementi che si trovano nelle posizioni dispari dell'array.

In [ ]:
import numpy as np

# Crea un array unidimensionale di numeri casuali tra 0 e 9
arr = np.random.randint(10, size=20)

# Filtra i valori maggiori di 5
mask = arr > 5
filtered_arr = arr[mask]

# Seleziona gli elementi nelle posizioni dispari
selected_arr = filtered_arr[1::2]

# Stampa il risultato
print(selected_arr)